Init redux
Timurkazan99/react-project pull request #15
Opened 2023-10-19 12:43 UTC by StaTov

create all reducers and selectors

2023-10-20 01:13 UTC, Timurkazan99 requested changes

2023-10-20 01:13 UTC, Timurkazan99 commented on frontend/src/store/thunks/country.ts
А где createAsyncThunk?

Почитай https://reactdev.ru/libs/redux-toolkit/#createasyncthunk_1

2023-10-20 01:13 UTC, Timurkazan99 commented on frontend/src/store/thunks/country.ts
> +  } catch (e) {
Перепиши на createAsyncThunk и добавь соответствующие extraReducer

2023-10-20 01:13 UTC, Timurkazan99 commented on frontend/src/store/thunks/country.ts
> +    dispatch(countrySlice.actions.countryFetchingByIdError(getErrorMessage(e)));
Перепиши на createAsyncThunk и добавь соответствующие extraReducer

2023-10-20 12:32 UTC, Timurkazan99 requested changes

2023-10-20 12:32 UTC, Timurkazan99 commented on frontend/src/store/reducers/userSlice.ts
> +  user: null,
Сделай поля login и password

2023-10-20 12:32 UTC, Timurkazan99 commented on frontend/src/store/thunks/country.ts
> +  },
Вы неси обработку ошибок в extrareducer'ы

2023-10-20 16:25 UTC, Timurkazan99 commented on frontend/src/store/reducers/countrySlice.ts
Продолжим в https://github.com/Timurkazan99/react-project/issues/18

2023-10-20 16:27 UTC, Timurkazan99 commented
Выглядит нормально)
Только перед мерджем нужно удалить из коммитов файлы AppRouter.tsx, Navbar.tsx и routes.tsx

2023-10-21 10:11 UTC, StaTov commented on frontend/src/types/types.ts
> +  password: string
Пока сохраняю промежуточный вариант.  Для валидации...

2023-10-21 10:50 UTC, Timurkazan99 approved these changes
Вернул навбар, роуты и аппроутер к первоночальному ввиду

2023-10-21 10:53 UTC, merged