6 создать navbar
Timurkazan99/react-project pull request #22
Opened 2023-10-22 17:58 UTC by StaTov

жду ваших комментариев,  коллеги)

2023-10-22 19:22 UTC, Timurkazan99 requested changes

2023-10-22 19:22 UTC, Timurkazan99 commented on frontend/src/components/Navbar/NavAuth.tsx
> +            <div className="Nav__divider">/</div>
Как по мне тут разделить выглядит лишним, лучше добавить эффект при наведении
![image](https://github.com/Timurkazan99/react-project/assets/43422137/54c0a16e-2c55-49bd-848c-64dc1c157631)

2023-10-22 19:22 UTC, Timurkazan99 commented on frontend/src/components/Navbar/index.tsx
> +import './navstyle.scss';
Лучше дать файлу имя как у компонента, то есть Navbar

2023-10-22 19:22 UTC, Timurkazan99 commented on frontend/src/components/Navbar/NavAuth.tsx
> +              {`${user.login} master`}
Зачем тут слово master?
![image](https://github.com/Timurkazan99/react-project/assets/43422137/f8cd27db-afd1-4e9b-a089-3ce2d5e4a107)
Выглядит странно

2023-10-22 19:22 UTC, Timurkazan99 commented on frontend/src/components/Navbar/index.tsx
> +        </div>
Лучше внешние дивы перенести в компонент, чтобы родительский выглядел опрятнее

2023-10-22 19:22 UTC, Timurkazan99 commented on frontend/src/components/Navbar/index.tsx
> +        </div>
Тут тоже

2023-10-22 19:22 UTC, Timurkazan99 commented on frontend/src/components/Navbar/navstyle.scss
Добавь эффекты на наведение на ссылки и кнопки

2023-10-22 20:14 UTC, StaTov commented on frontend/src/components/Navbar/NavAuth.tsx
> +            <div className="Nav__divider">/</div>
Убрал.

2023-10-22 20:14 UTC, StaTov commented on frontend/src/components/Navbar/index.tsx
> +import './navstyle.scss';
Исправил.

2023-10-22 20:18 UTC, StaTov commented on frontend/src/components/Navbar/NavAuth.tsx
> +              {`${user.login} master`}
Это слово для теста. Убрал

2023-10-22 20:21 UTC, StaTov commented on frontend/src/components/Navbar/index.tsx
> +        </div>
Здесь нельзя это выносить. по задумке так должно быть. Есть левое крыло и правое. и в них моджно добавлять компаненты.

2023-10-22 20:22 UTC, StaTov commented on frontend/src/components/Navbar/index.tsx
> +        </div>
Написал выше

2023-10-22 20:22 UTC, StaTov commented on frontend/src/components/Navbar/navstyle.scss
сделал

2023-10-23 09:29 UTC, DenisLatyshau commented
+

2023-10-23 09:40 UTC, DenisLatyshau approved these changes

2023-10-23 09:54 UTC, StaTov commented on frontend/src/components/Navbar/index.tsx
> +        </div>
Это просто контейнеры.

2023-10-23 10:15 UTC, Timurkazan99 approved these changes

2023-10-23 10:17 UTC, merged

2023-10-23 10:17 UTC, StaTov commented on frontend/src/components/Navbar/NavAuth.tsx
> +    </>
Изменил